name: Format source files
on: pull_request
jobs:
  format-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: "./src"
          clangFormatVersion: 11
          inplace: True

      - uses: EndBug/add-and-commit@v5
        with:
          add: './src'
          message: Formatted files via clang-format.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
